#Global Configs
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  
#Nginx - (Web Tier)
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.hostname = "web"
	web.vm.network "private_network", ip: "192.168.56.11"
  end
  
#Tomcat - (App Tier)
  config.vm.define "app" do |app|
    app.vm.box = "geerlingguy/centos7"
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.12"
	app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	end
  end
   
#RabbitMQ - (BE Tier)
  config.vm.define "rmq" do |rmq|
    rmq.vm.box = "geerlingguy/centos7"
	rmq.vm.hostname = "rmq"
    rmq.vm.network "private_network", ip: "192.168.56.13"
  end
  
#MemCache - (BE Tier)
  config.vm.define "mc" do |mc|
    mc.vm.box = "geerlingguy/centos7"
	mc.vm.hostname = "mc"
    mc.vm.network "private_network", ip: "192.168.56.14"
  end
  
#MySQL - (DB Tier)
  config.vm.define "db" do |db|
    db.vm.box = "geerlingguy/centos7"
	db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.15"
  end
end
